<?php
	return [
		'admin.' => ['title' => 'ダッシュボード', 'keyword' => '', 'description' => ''],

        'admin.company.index' => ['title' => '会社/店', 'keyword' => '', 'description' => ''],
        'admin.company.create' => ['title' => '会社/店', 'keyword' => '', 'description' => ''],
        'admin.company.store' => ['title' => '会社/店', 'keyword' => '', 'description' => ''],
        'admin.company.edit' => ['title' => '会社/店', 'keyword' => '', 'description' => ''],
        'admin.company.update' => ['title' => '会社/店', 'keyword' => '', 'description' => ''],
        'admin.company.end' => ['title' => '会社/店', 'keyword' => '', 'description' => ''],


        'admin.admin_user.index' => ['title' => '管理ユーザー', 'keyword' => '', 'description' => ''],
        'admin.admin_user.create' => ['title' => '管理ユーザー', 'keyword' => '', 'description' => ''],
        'admin.admin_user.store' => ['title' => '管理ユーザー', 'keyword' => '', 'description' => ''],
        'admin.admin_user.edit' => ['title' => '管理ユーザー', 'keyword' => '', 'description' => ''],
        'admin.admin_user.update' => ['title' => '管理ユーザー', 'keyword' => '', 'description' => ''],
        'admin.admin_user.end' => ['title' => '管理ユーザー', 'keyword' => '', 'description' => ''],

        'admin.user.index' => ['title' => 'ユーザー', 'keyword' => '', 'description' => ''],
        'admin.user.create' => ['title' => 'ユーザー', 'keyword' => '', 'description' => ''],
        'admin.user.store' => ['title' => 'ユーザー', 'keyword' => '', 'description' => ''],
        'admin.user.edit' => ['title' => 'ユーザー', 'keyword' => '', 'description' => ''],
        'admin.user.update' => ['title' => 'ユーザー', 'keyword' => '', 'description' => ''],
        'admin.user.end' => ['title' => 'ユーザー', 'keyword' => '', 'description' => ''],

        'admin.post.index' => ['title' => '投稿', 'keyword' => '', 'description' => ''],
        'admin.post.create' => ['title' => '投稿', 'keyword' => '', 'description' => ''],
        'admin.post.store' => ['title' => '投稿', 'keyword' => '', 'description' => ''],
        'admin.post.edit' => ['title' => '投稿', 'keyword' => '', 'description' => ''],
        'admin.post.update' => ['title' => '投稿', 'keyword' => '', 'description' => ''],
        'admin.post.end' => ['title' => '投稿', 'keyword' => '', 'description' => ''],

        'admin.language.index' => ['title' => '投稿', 'keyword' => '', 'description' => ''],
        'admin.language.create' => ['title' => '投稿', 'keyword' => '', 'description' => ''],
        'admin.language.store' => ['title' => '投稿', 'keyword' => '', 'description' => ''],
        'admin.language.edit' => ['title' => '投稿', 'keyword' => '', 'description' => ''],
        'admin.language.update' => ['title' => '投稿', 'keyword' => '', 'description' => ''],
        'admin.language.end' => ['title' => '投稿', 'keyword' => '', 'description' => ''],

        'admin.page.index' => ['title' => 'ページ生成', 'keyword' => '', 'description' => ''],
        'admin.page.create' => ['title' => 'ページ生成', 'keyword' => '', 'description' => ''],
        'admin.page.store' => ['title' => 'ページ生成', 'keyword' => '', 'description' => ''],
        'admin.page.edit' => ['title' => 'ページ生成', 'keyword' => '', 'description' => ''],
        'admin.page.update' => ['title' => 'ページ生成', 'keyword' => '', 'description' => ''],
        'admin.page.end' => ['title' => 'ページ生成', 'keyword' => '', 'description' => ''],

        'admin.qa.index' => ['title' => 'よくある質問', 'keyword' => '', 'description' => ''],
        'admin.qa.create' => ['title' => 'よくある質問', 'keyword' => '', 'description' => ''],
        'admin.qa.store' => ['title' => 'よくある質問', 'keyword' => '', 'description' => ''],
        'admin.qa.edit' => ['title' => 'よくある質問', 'keyword' => '', 'description' => ''],
        'admin.qa.update' => ['title' => 'よくある質問', 'keyword' => '', 'description' => ''],
        'admin.qa.end' => ['title' => 'よくある質問', 'keyword' => '', 'description' => ''],

        'company.event.index' => ['title' => 'イベント', 'keyword' => '', 'description' => ''],
        'company.event.create' => ['title' => 'イベント', 'keyword' => '', 'description' => ''],
        'company.event.store' => ['title' => 'イベント', 'keyword' => '', 'description' => ''],
        'company.event.edit' => ['title' => 'イベント', 'keyword' => '', 'description' => ''],
        'company.event.update' => ['title' => 'イベント', 'keyword' => '', 'description' => ''],
        'company.event.end' => ['title' => 'イベント', 'keyword' => '', 'description' => ''],
        'company.event.participation' => ['title' => 'イベント参加者', 'keyword' => '', 'description' => ''],

        'company.post.index' => ['title' => '記事', 'keyword' => '', 'description' => ''],
        'company.post.create' => ['title' => '記事', 'keyword' => '', 'description' => ''],
        'company.post.store' => ['title' => '記事', 'keyword' => '', 'description' => ''],
        'company.post.edit' => ['title' => '記事', 'keyword' => '', 'description' => ''],
        'company.post.update' => ['title' => '記事', 'keyword' => '', 'description' => ''],
        'company.post.end' => ['title' => '記事', 'keyword' => '', 'description' => ''],

        'company.user.index' => ['title' => 'ユーザー', 'keyword' => '', 'description' => ''],
        'company.user.create' => ['title' => 'ユーザー', 'keyword' => '', 'description' => ''],
        'company.user.store' => ['title' => 'ユーザー', 'keyword' => '', 'description' => ''],
        'company.user.edit' => ['title' => 'ユーザー', 'keyword' => '', 'description' => ''],
        'company.user.update' => ['title' => 'ユーザー', 'keyword' => '', 'description' => ''],
        'company.user.end' => ['title' => 'ユーザー', 'keyword' => '', 'description' => ''],
    ];
